image: node:lastest
pages:
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
      prefix: yarn
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
    - mkdir -p public
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
